---
title: "Trim and Denoise ASVs"
author: "Sarah Tanja"
format: gfm
toc: true
toc-title: Contents <i class="bi bi-bookmark-heart"></i>
toc-depth: 5
toc-location: left
bibliography: "../microbiome_bibtex.bib"
reference-location: margin
citation-location: margin
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,         # Display code chunks
  eval = FALSE,        # Evaluate code chunks
  warning = FALSE,     # Hide warnings
  message = FALSE,     # Hide messages
  comment = ""         # Prevents appending '##' to beginning of lines in code output
)
```

# Load packages
```{r}
library(knitr)
library(dplyr)
library(readr)
library(reticulate)
```

# Sequence files
- Here I am working with raw `.fastq.gz` files located in the `../data/` directory
- There are two `fastq.gz` files for each of the 63 samples, 1 forward read and 1 reverse read (R1 & R2)

# Metadata
- metadata for the samples are located at `../metadata/metadata.tsv`

```{r}
metadata <- read_tsv("../metadata/metadata.tsv")
```

